%YAML:1.0
---
model_type: KANNALA_BRANDT
camera_name: camera
image_width: 2448
image_height: 2048

projection_parameters:
  k2: -0.012118
  k3:  0.002096
  k4: -0.008513
  k5:  0.004579
  mu: 1251.692520
  mv: 1251.692520
  u0: 1260.118841
  v0: 1035.947448